/*
 * Smart Waste Segregation System - Arduino Sketch
 * -----------------------------------------------
 * This sketch receives classification result (from host Python or onboard TinyML)
 * and controls servo motors + buzzer + LCD.
 *
 * For full onboard TinyML (ESP32-CAM / Nano 33 BLE), replace the serial parsing
 * section with the TensorFlow Lite Micro inference code generated by Edge Impulse
 * or TensorFlow Lite for Microcontrollers.
 *
 * Hardware:
 *   - Servo 1 (Dry/Recyclable) -> Pin 9
 *   - Servo 2 (Metal)          -> Pin 10
 *   - Servo 3 (Organic)        -> Pin 11
 *   - Buzzer                   -> Pin 8
 *   - Moisture Sensor          -> A0
 *   - Metal Sensor (digital)   -> Pin 7
 *   - DHT22 (Decomposition)    -> Pin 6
 *   - Ultrasonic (optional)    -> Pins 4 & 5
 */

#include <Servo.h>
#include <DHT.h>
#include <LiquidCrystal_I2C.h>   // Optional LCD

// Pin definitions
#define SERVO_DRY_PIN     9
#define SERVO_METAL_PIN   10
#define SERVO_ORGANIC_PIN 11
#define BUZZER_PIN        8
#define MOISTURE_PIN      A0
#define METAL_SENSOR_PIN  7
#define DHT_PIN           6
#define DHT_TYPE          DHT22

// Objects
Servo servoDry;
Servo servoMetal;
Servo servoOrganic;
DHT dht(DHT_PIN, DHT_TYPE);
// LiquidCrystal_I2C lcd(0x27, 16, 2);  // Uncomment if using LCD

// Thresholds
const int MOISTURE_THRESHOLD = 500;   // Adjust after calibration

void setup() {
  Serial.begin(115200);
  
  servoDry.attach(SERVO_DRY_PIN);
  servoMetal.attach(SERVO_METAL_PIN);
  servoOrganic.attach(SERVO_ORGANIC_PIN);
  
  pinMode(BUZZER_PIN, OUTPUT);
  pinMode(METAL_SENSOR_PIN, INPUT);
  
  dht.begin();
  
  // Move servos to neutral position
  resetServos();
  
  Serial.println("Smart Waste Segregator Ready");
  Serial.println("Waiting for classification command...");
  // lcd.init(); lcd.backlight();
  // lcd.print("System Ready");
}

void loop() {
  // 1. Check for serial command from host / TinyML module
  if (Serial.available()) {
    String command = Serial.readStringUntil('\n');
    command.trim();
    command.toLowerCase();
    
    processClassification(command);
  }
  
  // 2. Optional: Periodic decomposition monitoring
  static unsigned long lastDhtRead = 0;
  if (millis() - lastDhtRead > 5000) {
    float temp = dht.readTemperature();
    float hum  = dht.readHumidity();
    if (!isnan(temp) && !isnan(hum)) {
      Serial.print("DECOMP_TEMP:");
      Serial.print(temp);
      Serial.print(",HUM:");
      Serial.println(hum);
    }
    lastDhtRead = millis();
  }
  
  // 3. Hybrid sensor backup (if no vision result)
  // int moisture = analogRead(MOISTURE_PIN);
  // bool isMetal = digitalRead(METAL_SENSOR_PIN);
  // ... add logic if needed
}

void processClassification(String cls) {
  Serial.print("Received class: ");
  Serial.println(cls);
  
  resetServos();
  delay(200);
  
  if (cls == "paper" || cls == "cardboard" || cls == "plastic") {
    // Dry / Recyclable
    servoDry.write(90);          // Open dry bin
    Serial.println("Action: Dry/Recyclable Bin");
    // lcd.clear(); lcd.print("Dry/Recyclable");
  }
  else if (cls == "metal") {
    servoMetal.write(90);
    Serial.println("Action: Metal Bin");
    // lcd.clear(); lcd.print("Metal Bin");
  }
  else if (cls == "organic") {
    servoOrganic.write(90);
    Serial.println("Action: Organic -> Decomposition Chamber");
    // lcd.clear(); lcd.print("Organic->Compost");
  }
  else if (cls == "battery") {
    // Hazardous alert
    digitalWrite(BUZZER_PIN, HIGH);
    delay(2000);
    digitalWrite(BUZZER_PIN, LOW);
    Serial.println("ALERT: Hazardous Battery Detected!");
    // lcd.clear(); lcd.print("BATTERY ALERT!");
  }
  else {
    Serial.println("Unknown class - Manual sorting required");
  }
  
  delay(2000);   // Keep flap open
  resetServos();
}

void resetServos() {
  servoDry.write(0);
  servoMetal.write(0);
  servoOrganic.write(0);
}

/*
 * NOTES FOR FULL ONBOARD TinyML:
 * 1. Use Edge Impulse → Deploy → Arduino Library
 * 2. Include the generated library and run inference on camera frame
 * 3. Call processClassification() with the predicted label
 * 4. For ESP32-CAM, follow Edge Impulse ESP-EYE / ESP32-CAM tutorials
 */
