# Generated by Django 6.1.1 on 2026-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastescan',
            name='green_coins',
            field=models.IntegerField(default=0),
        ),
    ]
