# Generated by Django 6.1.1 on 2026-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_wastescan_green_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastescan',
            name='carbon_credits',
            field=models.FloatField(default=0),
        ),
    ]
